name: ReUsableWorkflows

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_call:
    inputs:
      testinput:
        required: false
        type: string
  workflow_dispatch:
  pull_request_target:
    types: edited

jobs:
  compliance2:
    uses: k-sau/.github/.github/workflows/main.yml@main
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo Hello from Octo Organization
          echo ${{secrets.TESTING}}
          echo ${{ inputs.testinput }}
